trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Infra

pool:
  vmImage: ubuntu-latest

variables:
  resourcegroup: 'Automacao'
  storageaccount: 'automacaoterraform'
  blobcontainer: 'terraform'
  terraformstatekey: 'terraform.tfstate'

stages:
  - stage: tfvalidade
    jobs:
      - job: validade
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: Installer
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure'
              backendAzureRmResourceGroupName: '$(resourcegroup)'
              backendAzureRmStorageAccountName: '$(storageaccount)'
              backendAzureRmContainerName: '$(blobcontainer)'
              backendAzureRmKey: '$(terraformstatekey)'
          - task: TerraformTaskV4@4
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'

  - stage: tfdeploy
    condition: suceeded('tfvalidade')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps: 
          - task: TerraformInstaller@1
            displayName: Installer
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure'
              backendAzureRmResourceGroupName: '$(resourcegroup)'
              backendAzureRmStorageAccountName: '$(storageaccount)'
              backendAzureRmContainerName: '$(blobcontainer)'
              backendAzureRmKey: '$(terraformstatekey)'
          - task: TerraformTaskV4@4
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'

